name: tourist_assistive_app
description: A comprehensive tourist assistance application for Ethiopia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  animated_bottom_navigation_bar: ^1.3.3
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # Language Learning & Translation
  flutter_tts: ^4.2.3
  audioplayers: ^6.1.0
  # speech_to_text: ^6.6.0  # Temporarily disabled due to build issues
  
  # Google Cloud APIs
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.2
  
  # Advanced UI & Animations
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.8.0
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  permission_handler: ^11.4.0
  
  # Progress & Gamification
  percent_indicator: ^4.2.3
  circular_countdown_timer: ^0.2.3
  flutter_rating_bar: ^4.0.1
  
  # Chat & AI
  dio: ^5.9.0
  openai_dart: ^0.5.5
  chat_gpt_sdk: ^3.1.5
  flutter_chat_ui: ^2.9.0
  uuid: ^4.5.1
  markdown: ^7.1.1
  
  # Payment Integration
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  
  # Utilities
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  crypto: ^3.0.5
  
  # Internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
    - assets/icons/
    - EthiopiaHandbook.pdf
    - amhariclearning.pdf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ethio_assist_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ethio_assist_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/ethio_assist_logo.png"
  


