version: '3.8'

services:
  # PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg15
    container_name: tourist_db
    environment:
      POSTGRES_USER: tourist_admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: tourist_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tourist_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tourist_backend
    environment:
      DATABASE_URL: postgresql://tourist_admin:admin_password@postgres:5432/tourist_app_db
      SECRET_KEY: change-this-to-a-secure-random-string-min-32-chars
      ADMIN_EMAIL: kiru72fekadu@gmail.com
      ADMIN_PASSWORD: "12332122"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "alembic upgrade head &&
             python scripts/create_admin.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  # S3-compatible storage (MinIO)
  minio:
    image: minio/minio:latest
    container_name: tourist_storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
