// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaqU8wFE7xBWxcfoFN5dJvhA5cRoo6Hqs',
    appId: '1:664798138963:web:7b95c365fb79394774eca6',
    messagingSenderId: '664798138963',
    projectId: 'ethiopia-tourist-app-2024',
    authDomain: 'ethiopia-tourist-app-2024.firebaseapp.com',
    storageBucket: 'ethiopia-tourist-app-2024.firebasestorage.app',
    measurementId: 'G-123456789', // Analytics measurement ID for web
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqU8wFE7xBWxcfoFN5dJvhA5cRoo6Hqs',
    appId: '1:664798138963:android:86ef208b78f6207274eca6',
    messagingSenderId: '664798138963',
    projectId: 'ethiopia-tourist-app-2024',
    storageBucket: 'ethiopia-tourist-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqU8wFE7xBWxcfoFN5dJvhA5cRoo6Hqs',
    appId: '1:664798138963:ios:338cb9526e40af4374eca6',
    messagingSenderId: '664798138963',
    projectId: 'ethiopia-tourist-app-2024',
    storageBucket: 'ethiopia-tourist-app-2024.firebasestorage.app',
    iosBundleId: 'com.ethiopia.tourist.touristAssistiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaqU8wFE7xBWxcfoFN5dJvhA5cRoo6Hqs',
    appId: '1:664798138963:ios:338cb9526e40af4374eca6',
    messagingSenderId: '664798138963',
    projectId: 'ethiopia-tourist-app-2024',
    storageBucket: 'ethiopia-tourist-app-2024.firebasestorage.app',
    iosBundleId: 'com.ethiopia.tourist.touristAssistiveApp',
  );
}