name: tourist_admin_panel
description: Admin panel for Tourist Assistive App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.2
  
  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI Components
  fl_chart: ^0.66.0
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  
  # Audio
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.2
  
  # Navigation
  go_router: ^13.0.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
