@echo off
echo ========================================
echo    Tourist Assistive App - Auto Setup
echo ========================================
echo.

echo This script will help you set up the AI chatbot automatically.
echo.

REM Check if .env file exists
if exist .env (
    echo Found existing .env file
    echo.
    choice /C YN /M "Do you want to update it with new API keys"
    if errorlevel 2 goto :skip_env
) else (
    echo Creating new .env file...
)

echo.
echo ========================================
echo    API Key Setup
echo ========================================
echo.

echo 1. OpenAI API Key (Required for full AI functionality)
echo    - Visit: https://platform.openai.com/api-keys
echo    - Sign up or log in
echo    - Create a new API key
echo    - Copy the key (starts with sk-)
echo.

set /p OPENAI_KEY="Enter your OpenAI API key (or press Enter to skip): "

if "%OPENAI_KEY%"=="" (
    echo OpenAI API key skipped - using development mode
    set OPENAI_KEY=sk-dev-placeholder-key
) else (
    echo OpenAI API key configured
)

echo.
echo 2. Google Cloud API Key (Optional - for voice services)
echo    - Visit: https://console.cloud.google.com/
echo    - Enable Text-to-Speech and Speech-to-Text APIs
echo    - Create credentials
echo.

set /p GOOGLE_CLOUD_KEY="Enter your Google Cloud API key (or press Enter to skip): "

if "%GOOGLE_CLOUD_KEY%"=="" (
    echo Google Cloud API key skipped
    set GOOGLE_CLOUD_KEY=dev-google-cloud-key
) else (
    echo Google Cloud API key configured
)

echo.
echo 3. Google Maps API Key (Optional - for maps and location)
echo    - Visit: https://console.cloud.google.com/
echo    - Enable Maps JavaScript API
echo    - Create credentials
echo.

set /p GOOGLE_MAPS_KEY="Enter your Google Maps API key (or press Enter to skip): "

if "%GOOGLE_MAPS_KEY%"=="" (
    echo Google Maps API key skipped
    set GOOGLE_MAPS_KEY=dev-google-maps-key
) else (
    echo Google Maps API key configured
)

echo.
echo 4. Payment API Keys (Optional - for payment processing)
echo.

set /p TELEBIRR_KEY="Enter your Telebirr API key (or press Enter to skip): "
set /p SANTIMPAY_KEY="Enter your SantimPay API key (or press Enter to skip): "

if "%TELEBIRR_KEY%"=="" set TELEBIRR_KEY=dev-telebirr-key
if "%SANTIMPAY_KEY%"=="" set SANTIMPAY_KEY=dev-santimpay-key

echo.
echo ========================================
echo    Creating Configuration Files
echo ========================================
echo.

REM Create .env file
echo Creating .env file...
(
echo # Environment variables for Tourist Assistive App
echo # Generated by auto setup script
echo.
echo # OpenAI API Key - Required for AI Chatbot
echo OPENAI_API_KEY=%OPENAI_KEY%
echo.
echo # Google Cloud API Key - Required for Voice Services
echo GOOGLE_CLOUD_API_KEY=%GOOGLE_CLOUD_KEY%
echo.
echo # Google Maps API Key - Required for Maps and Location Services
echo GOOGLE_MAPS_API_KEY=%GOOGLE_MAPS_KEY%
echo.
echo # Google Translate API Key - Required for Translation Services
echo GOOGLE_TRANSLATE_API_KEY=dev-google-translate-key
echo.
echo # Telebirr API Key - Required for Payment Processing
echo TELEBIRR_API_KEY=%TELEBIRR_KEY%
echo.
echo # SantimPay API Key - Required for Payment Processing
echo SANTIMPAY_API_KEY=%SANTIMPAY_KEY%
) > .env

echo .env file created successfully!

REM Create gradle.properties file for Android
echo Creating gradle.properties file...
(
echo # Android configuration
echo GOOGLE_MAPS_API_KEY=%GOOGLE_MAPS_KEY%
echo.
echo # Build configuration
echo android.useAndroidX=true
echo android.enableJetifier=true
) > android/gradle.properties

echo gradle.properties file created successfully!

echo.
echo ========================================
echo    Testing Configuration
echo ========================================
echo.

echo Testing Flutter configuration...
flutter doctor

echo.
echo ========================================
echo    Setup Complete!
echo ========================================
echo.

echo Your API keys have been configured successfully!
echo.
echo Next steps:
echo 1. Run: flutter pub get
echo 2. Run: flutter run
echo 3. The app will automatically detect your API keys
echo 4. If you need to change keys later, use the Settings screen in the app
echo.

if "%OPENAI_KEY%"=="sk-dev-placeholder-key" (
    echo NOTE: You're using development mode for OpenAI.
    echo The AI chatbot will work with pre-programmed responses.
    echo To get full AI functionality, add a real OpenAI API key.
    echo.
)

echo Press any key to continue...
pause > nul

:skip_env
echo Setup completed!
echo.
echo You can now run the app with: flutter run
echo.
pause

















































